### ISSUE TITLE
v0.0.11でニコニ立体ちゃん(アリシア・ソリッド)以外のモデルが表示されない

### ISSUE THREAD

**Issue by come25136** [rdrgn/three-vrm#11]
v0.0.10では表示されるモデルがv0.0.11では表示されない不具合があります

モデルデータの読み込みは成功していてscene上には存在しているのですが、可視化されません

確認に使用したモデル: [http://3d.nicovideo.jp/works/td38002](http://3d.nicovideo.jp/works/td38002)
(他のモデルも試しましたが同様の現象が起こりました)

v0.0.10
![snapcrab_noname_2018-10-26_19-11-9_no-00](https://user-images.githubusercontent.com/12409412/47560408-1608f980-d953-11e8-8943-56d3013fad9d.png)

v0.0.11
![snapcrab_noname_2018-10-26_19-12-12_no-00](https://user-images.githubusercontent.com/12409412/47560409-1608f980-d953-11e8-8f51-f8ec666a9d53.png)

**Comment by reminjp** [comment]
ご報告ありがとうございます。多忙のために対応が遅くなってしまいました。

https://github.com/rdrgn/three-vrm/commit/f249ff7b15b7a2a5ad4f7018f909d6baeb817d5d 以降での不具合の再現を確認し原因を特定したので修正します。
