### ISSUE TITLE
Fix MToon shader

### ISSUE THREAD

**Issue by reminjp** [rdrgn/three-vrm#12]
![image](https://user-images.githubusercontent.com/9990535/52179829-4ef21d80-2822-11e9-94da-cbe3b4cccc73.png)

**Comment by reminjp** [comment]
![image](https://user-images.githubusercontent.com/9990535/52422065-b36def00-2b38-11e9-9c7b-34956316e320.png)

**Comment by reminjp** [comment]
The color of the hairpin is still rendered incorrectly.

**Comment by Taremin** [comment]
ヘアピンの色がおかしいのはおそらくここで名前ベースでマテリアルを参照しているため、別のマテリアルのはずが同じものを参照しているためではないでしょうか？(vrm.parser.json.materialsを見ると同じ名前のマテリアルが大量にある)
https://github.com/rdrgn/three-vrm/blob/48f287d1e2ad7e284aa4da7f08d8d82bdd8fd3ff/src/data/VRM.ts#L99-L101

**Comment by reminjp** [comment]
確かに、特に髪のマテリアルは大量にありますね……
検索に名前以外の情報も使うことを考えてみます。
